### ISSUE TITLE
Create a gig dashboard component that summarizes the types of jobs available.

### ISSUE THREAD

**Issue by craigbpeterson** [gig-central/gig-repo-1#226]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?: Feature request

###_Severity (1-4; 1 - not severe, 4 - very severe): 1
 
###_Priority (1-4; 1 - lowest priority, 4 - highest priority): 1

###_Synopsis - describe bug/task/future request, in more detail: 
This feature will be a component that can be loaded in any view, most likely the home page. It will display a summary of the types of jobs available. The idea will be to provide a visual reference for the number of jobs available in each given job title, for example.

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
This component will query the database and generate a visual based on the results.

###_Actual Behavior - what the behavior is instead, for bugs only: 

###_Steps to Repro the Issue, for bugs only:

###_Other Notes, for bug/task/future requests:

**Comment by thomaskise** [comment]
Adding this detail to clean-up Gig Central document:
Group by/having as basis: Here’s an SQL statement that currently works against the data tables to show the gigs by EmploymentType and city:
Test and fix defects

Select count(CompanyCity) as GigsInCity, EmploymentType, CompanyCity FROM Company c LEFT JOIN Gigs g ON c.CompanyID = g.CompanyID GROUP BY EmploymentType ORDER BY CompanyCity asc

Running the above from Adminer shows there is one type of gig per city.  We’ll need a few more ‘fake’ gigs to make this look more interesting!

In order to run raw SQL against CI, you can do this: $this->db->query('YOUR QUERY HERE');

I see this as being a method maybe named dashboard() that exists as a method in the Gig model.  Then this could be used as an individual page, or added to the home page, or even with parameters passed in, for example:

Gig->dashboard(‘location’,’EmploymentType’);

In which location is a filter as well as EmploymentType, etc.

**Comment by thomaskise** [comment]
I think this is MVP?
